// <auto-generated />
using DatabaseApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseApp.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("DatabaseApp.Data.DTO.EmployeeDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Department");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<decimal>("Salary");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new { ID = 1, Department = "Marketing", FirstName = "John", LastName = "Doe", Salary = 25000m },
                        new { ID = 2, Department = "Marketing", FirstName = "Peter", LastName = "Peterson", Salary = 27000m },
                        new { ID = 3, Department = "Engineering", FirstName = "Mark", LastName = "Harison", Salary = 35000m },
                        new { ID = 4, Department = "Engineering", FirstName = "David", LastName = "Peterson", Salary = 38000m },
                        new { ID = 5, Department = "Engineering", FirstName = "Dave", LastName = "Nickleson", Salary = 24000m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
